# Used for subscription emails (subscription_notifier.rb)
app_name:  <%= ENV['IDEAPI_APP_NAME'] || "ideapi" %>
from_email: <%= ENV['IDEAPI_SUPPORT_EMAIL'] || "support@ideapi.com" %>

# Used in account creation (account.rb)
base_domain: <%= ENV['IDEAPI_BASE_DOMAIN'] || "example.com" %>

# Set this to true if you want to require CC info when creating a trial account for a paid plan
require_payment_info_for_trials: <%= ENV['IDEAPI_TRIAL_PAYMENT_INFO'] || false %>

# Credit card gateway: One of brain_tree, authorize_net_cim, payment_express, or trust_commerce
gateway: <%= ENV['IDEAPI_TRIAL_PAYMENT_INFO'] || "payment_express" %>

# Used for accessing the site admin controllers, to manage plans,
# discounts, etc.  This is prepended to base_domain, so 'admin'
# here will allow admin.example.com to serve the admin interface.
admin_subdomain: <%= ENV['IDEAPI_ADMIN_SUBDOMAIN'] || "admin" %>

#AFcWxV21C7fd0v3bYYYRCpSSRl31APbm-.yrl0EagYpq-U7ci4a-MSdr