postgres: &postgres
  hostname: localhost
  adapter: postgresql
  username: vincent
  password: SpaceCakes82-

mysql: &mysql
  hostname: localhost
  adapter: mysql
  username: vincent
  password: SpaceCakes82-
development:
  database: ideapi_development
  <<: *mysql

test:
  database: ideapi_test
  <<: *mysql