development:
  login: 'demo'
  password: 'password'
production:
  login: <%= ENV['IDEAPI_GATEWAY_LOGIN'] || "demo" %>
  password: <%= ENV['IDEAPI_GATEWAY_PASSWORD'] || "password" %>
test:
  login: 'demo'
  password: 'password'
